global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi-delivery-platform"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "api-1:8000"
          - "api-2:8000"
          - "api-3:8000"
